[2024-09-29T14:15:47.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T14:15:47.717+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.gcs_to_bq_reorder scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-09-29T14:15:47.770+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.gcs_to_bq_reorder scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-09-29T14:15:47.778+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-09-29T14:15:47.853+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_reorder> on 2024-06-17 00:00:00+00:00
[2024-09-29T14:15:47.919+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'gcs_to_bq_reorder', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '823', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmphp0qvu7u']
[2024-09-29T14:15:47.920+0000] {standard_task_runner.py:91} INFO - Job 823: Subtask gcs_to_bq_reorder
[2024-09-29T14:15:47.936+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11957) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T14:15:47.937+0000] {standard_task_runner.py:63} INFO - Started process 12012 to run task
[2024-09-29T14:15:48.108+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.gcs_to_bq_reorder scheduled__2024-06-17T00:00:00+00:00 [running]> on host 71321b93f95e
[2024-09-29T14:15:48.531+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='gcs_to_bq_reorder' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-09-29T14:15:48.532+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T14:15:48.553+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-29T14:15:48.580+0000] {base.py:84} INFO - Using connection ID 'my-gcp-conn' for task execution.
[2024-09-29T14:15:48.593+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-09-29T14:15:48.819+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'madt-finalproject', 'datasetId': 'finalproject_data', 'tableId': 'reorder'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://storage-madt-finalproject/reorder.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-09-29T14:15:48.820+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_gcs_to_bq_reorder_2024_06_17T00_00_00_00_00_16a9c8eda9db37a14112da44a1cd4c48
[2024-09-29T14:15:50.329+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T14:15:50.332+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://storage-madt-finalproject/reorder.csv; reason: notFound, message: Not found: URI gs://storage-madt-finalproject/reorder.csv
[2024-09-29T14:15:50.354+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=gcs_to_bq_reorder, execution_date=20240617T000000, start_date=20240929T141547, end_date=20240929T141550
[2024-09-29T14:15:50.403+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 823 for task gcs_to_bq_reorder (404 Not found: URI gs://storage-madt-finalproject/reorder.csv; reason: notFound, message: Not found: URI gs://storage-madt-finalproject/reorder.csv; 12012)
[2024-09-29T14:15:50.477+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-29T14:15:51.095+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T14:15:51.114+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
