[2024-09-29T14:15:37.347+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T14:15:37.442+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.gcs_to_bq_invoice_type scheduled__2024-06-15T00:00:00+00:00 [queued]>
[2024-09-29T14:15:37.501+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.gcs_to_bq_invoice_type scheduled__2024-06-15T00:00:00+00:00 [queued]>
[2024-09-29T14:15:37.502+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-09-29T14:15:37.578+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_invoice_type> on 2024-06-15 00:00:00+00:00
[2024-09-29T14:15:37.628+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'gcs_to_bq_invoice_type', 'scheduled__2024-06-15T00:00:00+00:00', '--job-id', '810', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpkcs5y4in']
[2024-09-29T14:15:37.636+0000] {standard_task_runner.py:91} INFO - Job 810: Subtask gcs_to_bq_invoice_type
[2024-09-29T14:15:37.663+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11906) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T14:15:37.668+0000] {standard_task_runner.py:63} INFO - Started process 11936 to run task
[2024-09-29T14:15:37.898+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.gcs_to_bq_invoice_type scheduled__2024-06-15T00:00:00+00:00 [running]> on host 71321b93f95e
[2024-09-29T14:15:38.365+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='gcs_to_bq_invoice_type' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-15T00:00:00+00:00'
[2024-09-29T14:15:38.368+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T14:15:38.412+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-29T14:15:38.439+0000] {base.py:84} INFO - Using connection ID 'my-gcp-conn' for task execution.
[2024-09-29T14:15:38.440+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-09-29T14:15:38.740+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'madt-finalproject', 'datasetId': 'finalproject_data', 'tableId': 'invoice_type'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://storage-madt-finalproject/invoice_type.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-09-29T14:15:38.747+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_gcs_to_bq_invoice_type_2024_06_15T00_00_00_00_00_d5028771a54a1d59658a056a3e90f627
[2024-09-29T14:15:40.180+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T14:15:40.183+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://storage-madt-finalproject/invoice_type.csv; reason: notFound, message: Not found: URI gs://storage-madt-finalproject/invoice_type.csv
[2024-09-29T14:15:40.206+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=gcs_to_bq_invoice_type, execution_date=20240615T000000, start_date=20240929T141537, end_date=20240929T141540
[2024-09-29T14:15:40.291+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 810 for task gcs_to_bq_invoice_type (404 Not found: URI gs://storage-madt-finalproject/invoice_type.csv; reason: notFound, message: Not found: URI gs://storage-madt-finalproject/invoice_type.csv; 11936)
[2024-09-29T14:15:40.357+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-29T14:15:40.451+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T14:15:40.465+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
