[2024-09-29T09:11:02.577+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T09:11:02.679+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.gcs_to_bq_product scheduled__2024-05-28T00:00:00+00:00 [queued]>
[2024-09-29T09:11:02.743+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.gcs_to_bq_product scheduled__2024-05-28T00:00:00+00:00 [queued]>
[2024-09-29T09:11:02.743+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-09-29T09:11:03.605+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_product> on 2024-05-28 00:00:00+00:00
[2024-09-29T09:11:03.683+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'gcs_to_bq_product', 'scheduled__2024-05-28T00:00:00+00:00', '--job-id', '460', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp89e_ltpz']
[2024-09-29T09:11:03.688+0000] {standard_task_runner.py:91} INFO - Job 460: Subtask gcs_to_bq_product
[2024-09-29T09:11:03.687+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=32117) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T09:11:03.692+0000] {standard_task_runner.py:63} INFO - Started process 32203 to run task
[2024-09-29T09:11:03.949+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.gcs_to_bq_product scheduled__2024-05-28T00:00:00+00:00 [running]> on host 71321b93f95e
[2024-09-29T09:11:04.199+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='gcs_to_bq_product' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-28T00:00:00+00:00'
[2024-09-29T09:11:04.201+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T09:11:04.259+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-29T09:11:04.311+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-09-29T09:11:04.336+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-09-29T09:11:04.576+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: finalproject_data.product; using project "madt-finalproject"
[2024-09-29T09:11:04.581+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'madt-finalproject', 'datasetId': 'finalproject_data', 'tableId': 'product'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://storage-madt-finalproject/product.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-09-29T09:11:04.582+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_gcs_to_bq_product_2024_05_28T00_00_00_00_00_0d10dbb029b301de1f0d762858c9dc96
[2024-09-29T09:11:07.037+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T09:11:07.042+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 3473; errors: 1; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 3473; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://storage-madt-finalproject/product.csv, message: Error while reading data, error message: Bad character (ASCII 0) encountered.; line_number: 1756 byte_offset_to_start_of_line: 175536 column_index: 2 column_name: "Part Description" column_type: STRING value: "Shamir Autograph ..." File: gs://storage-madt-finalproject/product.csv
[2024-09-29T09:11:07.070+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=gcs_to_bq_product, execution_date=20240528T000000, start_date=20240929T091102, end_date=20240929T091107
[2024-09-29T09:11:07.136+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 460 for task gcs_to_bq_product (400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 3473; errors: 1; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 3473; errors: 1; max bad: 0; error percent: 0; reason: invalid, location: gs://storage-madt-finalproject/product.csv, message: Error while reading data, error message: Bad character (ASCII 0) encountered.; line_number: 1756 byte_offset_to_start_of_line: 175536 column_index: 2 column_name: "Part Description" column_type: STRING value: "Shamir Autograph ..." File: gs://storage-madt-finalproject/product.csv; 32203)
[2024-09-29T09:11:07.221+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-29T09:11:07.294+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T09:11:07.315+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
